services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - .env
    stdin_open: true
    tty: true
    restart: unless-stopped 
