export const Errors = {
    METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    WRONG_CREDENTIALS: "WRONG_CREDENTIALS",
    EMAIL_IN_USE: "EMAIL_IN_USE",
    DATABASE_ERROR: "DATABASE_ERROR",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    UNAUTHORIZED: "UNAUTHORIZED",
} as const;

export type ErrorCode = (typeof Errors)[keyof typeof Errors];
